"""empty message

Revision ID: 29517e5d6f1f
Revises: ae07ac40a9cb
Create Date: 2022-04-17 19:42:35.985023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29517e5d6f1f'
down_revision = 'ae07ac40a9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
